### ISSUE TITLE
about usage

### ISSUE THREAD

**Issue by JiHaoqina** [lsqpku/img2img#7]
hi, how can i directly test my own image? Thanks!

**Comment by lsqpku** [comment]
you have to train the model using your own image (check the flag.dataset in main6.py) firstly.

**Comment by JiHaoqina** [comment]
@lsqpku is it convenient to share your checlpoint file？Thanks!

**Comment by JiHaoqina** [comment]
@lsqpku thanks, I'm training my own datasets now
